### PR TITLE
Add iframe to show good-quality data

### LINKED ISSUE #202: Add iframe to show good-quality data
It would be nice to embed a nifti viewer in our RTD, to show examples of good quality data.

Technologies to embed niftis include:
- https://brainsprite.github.io/ --> looks like this is the winner! 🎉   (and made by Pierre Bellec)
- https://github.com/rii-mango/Papaya
- https://github.com/FNNDSC/ami
- https://brainbrowser.cbrain.mcgill.ca/

or via Python code:
- NiftiWidget: https://github.com/jcohenadad/GBM8378/blob/master/lab3-irm/gbm8378-lab3-irm.ipynb

### PR DESCRIPTION
**Pull request by alexfoias**
Build here: 
https://spine-generic.readthedocs.io/en/af-202-good-data/data-acquisition.html

To test:
```
git checkout af/202-good-data
cd docs
make html
cd /_build/html
open -a "Google Chrome" data-acquisition.html
```

Fixes #202

### CODE REVIEW

**Comment by jcohenadad** [comment]
I tried your version https://github.com/spine-generic/spine-generic/pull/218/commits/753fe810177a6de07013651c56a04dbfa5e64e11, and it is not as good as what you posted in https://github.com/spine-generic/spine-generic/issues/202#issuecomment-690677535. The problem is that in https://github.com/spine-generic/spine-generic/pull/218/commits/753fe810177a6de07013651c56a04dbfa5e64e11, images are resampled, which prevents from appreciating the native spatial resolution. 

Until Pierre fixes the bug on brainsprite, could you try to resample the images only in the z direction? (ie. making it isotropic resolution, e.g. 0.9x0.9x0.9 for the MT scans)

**Comment by alexfoias** [comment]
@jcohenadad I resampled the MTS images in https://github.com/spine-generic/spine-generic/pull/218/commits/6cb02f38b2356714ee46cec4c89fa81595bebf2b. Should I also resample the other ones (T1w, T2w, T2star) because they look downsampled as well?

**Comment by jcohenadad** [comment]
> Should I also resample the other ones (T1w, T2w, T2star) because they look downsampled as well?

only resample when res is anisotropic, right? (ie: to avoid the squeezing effect). https://github.com/spine-generic/spine-generic/issues/202#issuecomment-690677535 did not look downsampled to me

**Comment by alexfoias** [comment]
@jcohenadad 
I updated the images. I had to resample only the T2star.

Could you please check ?

**Comment by jcohenadad** [comment]
@alexfoias feedback on bdee084e:
- looks gorgeous 🎉 
- i would definitely make each panel bigger (it is difficult to see the spinal cord, and there is space on the web page)
- on the T2* the blue cross does not appear (at least on my browser)
- could you reorganize the sections:
  - Data conversion: DICOM to BIDS
  - Checking acquisition parameters
  - Ethics and anonymization
  - Multi-center data
  - Example of datasets  --> this is where you can put your images

**Comment by alexfoias** [comment]
@jcohenadad I have triggered a new build. You can try it on the link: https://spine-generic.readthedocs.io/en/af-202-good-data/data-acquisition.html

For T2* i have the same problem with the cross.

**Comment by jcohenadad** [comment]
@alexfoias i've checked a7c4c13e and this is very cool! A few comments:
- don't worry about the cross on the T2*, that's a minor issue
- How come the T2* and all GRE data seem "rotated" when displayed? for example, you can see on the sagittal image that the bottom makes an angle. Is there a possibility to display the images without such rotation/resampling? maybe try to turn off the background/template option?
- Could you please also show the mean DWI image?

Thanks!

**Comment by alexfoias** [comment]
> * How come the T2* and all GRE data seem "rotated" when displayed? for example, you can see on the sagittal image that the bottom makes an angle. Is there a possibility to display the images without such rotation/resampling? maybe try to turn off the background/template option?

T2* is the only scan that has the orientation LAS, all the other ones are RAS. I didn't rotate the images.. We don't have a background for any of the images. 

> * Could you please also show the mean DWI image?

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/065defdf3de144adbca8d437ce48dafeb4980dcf .

> * Could you add the subject ID next to each contrast

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/065defdf3de144adbca8d437ce48dafeb4980dcf .

**Comment by jcohenadad** [comment]
> How come the T2* and all GRE data seem "rotated" when displayed? for example, you can see on the sagittal image that the bottom makes an angle. Is there a possibility to display the images without such rotation/resampling? maybe try to turn off the background/template option?
T2* is the only scan that has the orientation LAS, all the other ones are RAS. I didn't rotate the images.. We don't have a background for any of the images.

right, but that didn't explain what's going on for the T2* and GRE scans (ie all the MTS). Do you see what i mean by "rotated"? there is something going on here. Maybe if you try to reorient to RAS?

**Comment by alexfoias** [comment]
I tried to reorient to RAS. I even tried LAS or RIP. They always orient the image from the iframe in the same way.

**Comment by jcohenadad** [comment]
comments from 405e75ac:
- can you remove "anatomical scan" from the DWI image
- on the DWI image: can you use resampling as you did for the GRE scans (anisotropic resolution)
- about the GRE and T2* orientations: ok, let's see if we can at least improve the appearance: would it be possible to zoom in a little, so we can better see the spinal cord? it looks very small

**Comment by alexfoias** [comment]
> * can you remove "anatomical scan" from the DWI image

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/f20b6098d8899539186a56e365a0f6f75e13a60d.

> * on the DWI image: can you use resampling as you did for the GRE scans (anisotropic resolution)

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/f20b6098d8899539186a56e365a0f6f75e13a60d.

> * about the GRE and T2* orientations: ok, let's see if we can at least improve the appearance: would it be possible to zoom in a little, so we can better see the spinal cord? it looks very small

I tried to use the variable **dim** in **viewer_substitute**  and **width, height** in **bsprite.transform**, but nothing seemed to zoom . Should I do a follow-up on the https://github.com/brainsprite/brainsprite/issues/98#issuecomment-690815406 ?

**Comment by jcohenadad** [comment]
> I tried to use the variable **dim** in **viewer_substitute** and **width, height** in **bsprite.transform**, but nothing seemed to zoom . Should I do a follow-up on the [brainsprite/brainsprite#98 (comment)](https://github.com/brainsprite/brainsprite/issues/98#issuecomment-690815406) ?

no, they are too busy

DWI: I think you included the b=0 image in the average (not only the DWI data), as can be seen below (we see the vessels, which should not happen with DWI weighting):
image

Regarding the zoom: could you please crop the GRE data, eg: X: -56, +56 and Y: -60, +100? That should make the spinal cord bigger

**Comment by alexfoias** [comment]
> DWI: I think you included the b=0 image in the average (not only the DWI data), as can be seen below (we see the vessels, which should not happen with DWI weighting):

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/8f6ddbdae62ea30321e85baa98a655f758d02426.

I had to separate the dwi images
```
sct_dmri_separate_b0_and_dwi -i /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi.nii.gz -o /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi_separated.nii.gz -bvec /Users/alfoi/code/data-multi-subject/sub-barcelona04/dwi/sub-barcelona04_dwi.bvec
sct_maths -i /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi_separated.nii.gz/sub-barcelona04_dwi_dwi.nii.gz -mean t -o /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi_mean_new.nii.gz
sct_resample -i /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi_mean_new.nii.gz  -mm 0.9x0.9x0.9 -o /Users/alfoi/Desktop/DATA/RAW/contrasts_good/sub-barcelona04_dwi_mean_new_isotropic.nii.gz
```


> Regarding the zoom: could you please crop the GRE data, eg: X: -56, +56 and Y: -60, +100? That should make the spinal cord bigger

Done in https://github.com/spine-generic/spine-generic/pull/218/commits/3262a815b667c23adb15fee2c14a2156a59bddf3.

**Comment by jcohenadad** [comment]
>> Regarding the zoom: could you please crop the GRE data, eg: X: -56, +56 and Y: -60, +100? That should make the spinal cord bigger
> Done in 3262a81.

hum, it seems much more cropped than -56/56 (it shows -20/20). COuld you please try with a less aggressive cropping? ppl need to have an overview of the data as well-- thanks!

**Comment by alexfoias** [comment]
@jcohenadad Could you please check the new images ?

**Comment by jcohenadad** [comment]
> @jcohenadad Could you please check the new images ?

this is perfect! could you pls do the same for the T2* data-- thanks

**Comment by jcohenadad** [comment]
also pls remove "anatomical scan"

**Comment by alexfoias** [comment]
@jcohenadad Done. Not sure if you want it more larger for T2star.

**Comment by jcohenadad** [comment]
i still see the "anatomical scan":

image

(pls remove everywhere)

also, can you make the T2* look like the other MTS scans (currently it is smaller):

image

**Comment by jcohenadad** [comment]
can you also please remove the colorbars?

**Comment by alexfoias** [comment]
@jcohenadad done. I think the best practice is to open the link in a new page incognito in order to grab the latest updates.

**Review by jcohenadad — APPROVED** [review]
Awesome 👍

**Comment by jcohenadad** [comment]
@alexfoias could you please document how you generated the html at the top of this PR?

**Comment by alexfoias** [comment]
I added the code.

**Pull request merged**
