### PR TITLE
add bidsconfig for dwi error

### PR DESCRIPTION
**Pull request by alexfoias**

### CODE REVIEW

**Comment by alexfoias** [comment]
when running bids-valiadator use `bids-validator /path/to/bids -c /path/to/bidsconfig.json`

**Comment by jcohenadad** [comment]
@alexfoias why did you call this file `bidsconfig.json` instead of `.bidsignore`, as per the [BIDS convention](https://github.com/bids-standard/bids-validator#bidsignore)?

**Comment by alexfoias** [comment]
`.bidsignore` includes file types not yet supported by BIDS specification.

For the errors you have to use the `bidsconfig.json` as explained here https://github.com/bids-standard/bids-validator#configuration.

I saw some other datasets on the open neuro platform, some have warnings. I think it should be good as long as we don't have errors when running the `bids-validator`

**Comment by jcohenadad** [comment]
> .bidsignore includes file types not yet supported by BIDS specification.

yup! that's precisely what we want to do here: add the b0 file because not supported by BIDS (yet).

**Comment by alexfoias** [comment]
This PR can be closed since we'll use the solution stated here.

> > .bidsignore includes file types not yet supported by BIDS specification.
> 
> yup! that's precisely what we want to do here: add the b0 file because not supported by BIDS (yet).

**Comment by jcohenadad** [comment]
> This PR can be closed

you meant close without merging, right?

**Comment by alexfoias** [comment]
Yes, close without merging.

**Pull request closed without merging**
