### PR TITLE
Compute ANOVAs and post-hoc tests across vendors and within vendors

### LINKED ISSUE #184: generate_figure: Compute statistics across/within vendors
It would be useful to compute ANOVAs and t-tests to assess significant differences across vendors and within vendors.

### PR DESCRIPTION
**Pull request by jcohenadad**
This PR add ANOVAs and post-hoc analyses to test differences across and within vendors.

Results are added on the figure (traditional * for significance) and a log file with stats is generated.

Example of output:
~~~
Processing: csa-SC_T1w.csv
Loop across subjects: 100%|################| 162/162 [00:00<00:00, 832.31iter/s]
Subjects removed: ['sub-mountSinai03', 'sub-oxfordFmrib04']
ANOVA[site] for GE: F_onewayResult(statistic=1.168691428099702, pvalue=0.3667655828074303)
ANOVA[site] for Philips: F_onewayResult(statistic=0.48241317679423434, pvalue=0.8360475154248015)
ANOVA[site] for Siemens: F_onewayResult(statistic=0.9913675081564359, pvalue=0.48983410315800957)
ANOVA[vendor]: F_onewayResult(statistic=7.391803673588589, pvalue=0.0018970826314503827)
Tukey Honestly Significant Difference (HSD):
 Multiple Comparison of Means - Tukey HSD, FWER=0.05  
======================================================
 group1  group2 meandiff p-adj   lower   upper  reject
------------------------------------------------------
     GE Philips   6.0303  0.004  1.7487 10.3119   True
     GE Siemens   5.2944 0.0024  1.7278  8.8609   True
Philips Siemens  -0.7359 0.8252 -3.9142  2.4424  False
------------------------------------------------------
Created: fig_csa_t1.png
~~~

Other changes include:
- generate log file (`log_stats.txt`) under path results.
- show 95% CI with flag -show-ci
- individual subjects are now displayed by default. To not display them, use flag `-no-sub`

Fixes #184

### CODE REVIEW

**Comment by jcohenadad** [comment]
I implemented the 95% confidence interval and displayed it as the shaded rectangle, for each vendor, instead of the standard deviation. But at the end, I think I prefer to stick to the SD, because it is a less biased representation of the dispersion (the 95CI decreases with the number of sites, which is not favorable for vendors with less sites, e.g. GE).

**with STD:**
fig_csa_t1_STD

**with 95% CI:**
fig_csa_t1_95CI

**Comment by evaalonsoortiz** [comment]
I would go for displaying the SD, I think it coneys information that is more interesting for potential users of the protocol.

**Comment by jcohenadad** [comment]
How about keeping the two? (95% CI in red lines):

fig_csa_t1

**Comment by evaalonsoortiz** [comment]
I'm not crazy about it. But now that I think about it, I guess the CI is relevant for users, particularly if they're scanning in pathology and find a different group average ... If you decide to go for it, I like the last plot best.

**Comment by jcohenadad** [comment]
> I'm not crazy about it.

me neither... it's too "heavy". Let's leave it out for now and see what people say.

**Comment by jcohenadad** [comment]
95% CI is now an optional flag `-show-ci` edb9961

**Review by valosekj — APPROVED** [review]
Tested and works fine 👍

**Pull request merged**
