### PR TITLE
BIDS dataset validator

### PR DESCRIPTION
**Pull request by alexfoias**
This validator is a modified version of [bids-validator](https://github.com/bids-standard/bids-validator).

-  **dataset_validator** is used to check an individual BIDS dataset.
   Usage: `python dataset_validator.py -d PATH_TO_INDIVIDUAL_BIDS_DATASET`

- **wrapper_dataset_validator** is used to loop within a root path which hosts multiple BIDS datasets. 
   Usage: `python wrapper_dataset_validator.py -d PATH_TO_ROOT_BIDS_DATASETS`

### CODE REVIEW

**Comment by jcohenadad** [comment]
in [your usage](https://github.com/sct-pipeline/spine_generic/pull/19#issue-254040573), you meant `-d`, not `-r`, right?

**Comment by jcohenadad** [comment]
@alexfoias can you please give more details about what was modified from the original [bids-validator](https://github.com/bids-standard/bids-validator)?
Notably, i am trying to understand what is the specificity of this validator wrt. the spine_generic BIDS convention.

**Comment by alexfoias** [comment]
Changes in **bids_validator/rules/file_level_rules.json**:
- change in regexp `acq-[a-zA-Z0-9]` --`> acq-(@@@_mts_ext_@@@)`
From:
`
"regexp": "^\\/(sub-[a-zA-Z0-9]+)\\/(?:(ses-[a-zA-Z0-9]+)\\/)?anat\\/\\1(_\\2)?(?:_acq-[a-zA-Z0-9]+)?(?:_ce-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?_(?:@@@_anat_suffixes_@@@)\\.(@@@_anat_ext_@@@)$"
`
To:
`
    "regexp": "^\\/(sub-[a-zA-Z0-9]+)\\/(?:(ses-[a-zA-Z0-9]+)\\/)?anat\\/\\1(_\\2)?(?:_acq-(@@@_mts_ext_@@@)+)?(?:_ce-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?_(?:@@@_anat_suffixes_@@@)\\.(@@@_anat_ext_@@@)$"
  `
- add token for MTS
`
  "tokens": {
      "@@@_anat_suffixes_@@@": ["MTS"],
       "@@@_mts_ext_@@@": ["MTon", "MToff", "T1w"]
    }
`

Changes in **bids_validator/rules/top_level_rules.json**:
- add token for MTS
`
  "tokens": {
      "@@@_anat_suffixes_@@@": ["MTS"]}
`

**Comment by alexfoias** [comment]
@jcohenadad I fixed the parameter for `-d` in the latest commit.

**Comment by alexfoias** [comment]
The current implementation only checks if a file path appropriate for BIDS. I will add the top level verification ( the existence of: /dataset_description.json, /participants.tsv, /participants.json)

**Comment by alexfoias** [comment]
I added top level file verification.

**Comment by jcohenadad** [comment]
@alexfoias what is the status of this PR? maybe we should instead move the checking in this repository, and have both data-spine-generic import this repository during CI? (to avoid duplicating the code across the two dataset repositories)

**Comment by alexfoias** [comment]
Yes I agree https://github.com/spine-generic/data-single-subject/pull/3 should be implemented in this repo. I'll clean everything up and use `pybids` for all the tests because for the moment it's a cocktail of scripts. And as you said, for every dataset the CI will use the code from this repo to validate the data, this avoids duplication.

**Comment by alexfoias** [comment]
Each dataset will be verified in CI as listed in the travis config here:
https://github.com/spine-generic/data-single-subject/blob/af/acq_param_ci/.travis.yml#L37

We can close this PR.

**Comment by jcohenadad** [comment]
> Each dataset will be verified in CI as listed in the travis config here:
> https://github.com/spine-generic/data-single-subject/blob/af/acq_param_ci/.travis.yml#L37
> 
> We can close this PR.

and where does this "bids-validator" script come from? why closing this PR? (are all the files modified here to be dropped?). More context is needed

**Comment by alexfoias** [comment]
On Travis we are installing the latest version of `bids-validator` available here https://www.npmjs.com/package/bids-validator. For the moment, I had to add the MTS scans under `.bidsignore` until BEP001 will be merged to the specifications.
We won't need the wrapper because this will be done using travis CI.

**Pull request closed without merging**
